# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: intzero's Blog
author: intzero
email: intzero@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  程序媛/小硕/外协/折腾/技术宅
url: http://lszero.com # the base hostname & protocol for your site, e.g. http://example.com
sitesearchurl: lszero.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Markdown Processors
markdown: kramdown

plugins:
  - jekyll-paginate
paginate: 5
paginate_path: "/pages:num/"

mathjax: false

excerpt_separator: <!-- more -->

permalink: /:categories/:title.html

social_media:
  github_url: https://github.com/lszero
  weibo_url: http://weibo.com/u/2313016370
  zhihu_url: https://www.zhihu.com/people/lszero
  twitter_url: https://twitter.com/_lszero
  lofter_url: http://intzero.lofter.com/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
